name: Sync to Hugging Face Hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to HF
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "git@github.com"
          git config --global user.name "GitHub Actions"
          git remote add hf https://piyushqweh:$HF_TOKEN@huggingface.co/spaces/piyushqweh/bulkdns-api
          git push --force hf main > hf_push.log 2>&1 || (cat hf_push.log && exit 1)

      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: push-logs
          path: hf_push.log
